server:
  port: 8080
  tomcat:
    threads:
      max: 200
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:4000/db_cake_shop}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        order_inserts: true
        order_updates: true
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    enabled: true
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT:6379}
      password: ${REDISPASSWORD}
      url: ${REDIS_URL}
    elasticsearch:
      uris: http://localhost:9200

open:
  api:
    title: API Documentation
    version: v1.1.0
    description: API-Service
    serverUrl: ${SPRING_SERVER_URL}
    serverName: Server Test

jwt:
  signerKey: ${SECURITY_SIGNER_KEY}
  valid-duration: 7    # 7 ngày cho access token
  refreshable-duration: 30  # 30 ngày cho access token

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${SECURITY_REDIRECT_URI}

payment:
  vnPay:
    url: ${PAY_URL}
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    returnUrl: ${RETURN_URL}
    version: ${VERSION}
    command: ${COMMAND}
    orderType: ${ORDER_TYPE}
  momo:
    partner-code: MOMO
    redirect-url: http://localhost:8080/api/v1/order/ipn-handler
    ipn-url: http://localhost:8080/api/v1/order/ipn-handler
    access-key: F8BBA842ECF85
    secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
    request-type: payWithMethod
    end-point: https://test-payment.momo.vn/v2/gateway/api